# Generated by Django 2.2 on 2020-03-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_required',
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('CHOICE', 'CHOICE'), ('TEXT', 'TEXT')], max_length=10),
        ),
    ]
