# Generated by Django 2.2 on 2020-03-18 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20200318_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='type',
        ),
    ]
